node_ops = [
    "Exchange10",
    "Exchange20",
    "Exchange11",
    "Exchange21",
    "Exchange22",
    "SwapTails",
]


route_ops = [
    "SwapStar",
]


[genetic]
repair_probability = 0.50
nb_iter_no_improvement = 20_000


[population]
min_pop_size = 25
generation_size = 40
nb_elite = 4
nb_close = 5
lb_diversity = 0.1
ub_diversity = 0.5


[neighbourhood]
weight_wait_time = 0
weight_time_warp = 0
nb_granular = 20
symmetric_proximity = true
symmetric_neighbours = true


[penalty]
init_load_penalty = 20
init_time_warp_penalty = 0
repair_booster = 12
solutions_between_updates = 100
penalty_increase = 1.25
penalty_decrease = 0.85
target_feasible = 0.43
